apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: quotes-service
spec:
  selector:
    app: quotes-service
  ports:
    - protocol: "TCP"
      port: 8083 # The port that the service is running on in the cluster
      targetPort: 8083 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: quotes-service
spec:
  selector:
    matchLabels:
      app: quotes-service
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: quotes-service
    spec:
      containers:
        - name: quotes-service
          image: quotes-service # Image that will be used inside the container in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8083 # The port that the container is running on in the cluster
